// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNsLJ9xnkMiLwc_xZ5QPFKs0SCVmD1o4',
    appId: '1:874543556897:web:b6310941a02070527eb660',
    messagingSenderId: '874543556897',
    projectId: 'ddelivery-app',
    authDomain: 'ddelivery-app.firebaseapp.com',
    storageBucket: 'ddelivery-app.firebasestorage.app',
    measurementId: 'G-DWT4S49Q47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIEOR3eZ8-yJZLczYczGczQGYXqDf1tQc',
    appId: '1:874543556897:android:88eccd326ffd1e177eb660',
    messagingSenderId: '874543556897',
    projectId: 'ddelivery-app',
    storageBucket: 'ddelivery-app.firebasestorage.app',
  );
}
